# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dinossauro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_br', models.TextField()),
                ('custo_individual', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('f_alimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Alimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='f_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Genero'),
        ),
        migrations.AddField(
            model_name='dinossauro',
            name='f_especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Especie'),
        ),
        migrations.AddField(
            model_name='dinossauro',
            name='f_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Genero'),
        ),
        migrations.AddField(
            model_name='dinossauro',
            name='f_ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Ordem'),
        ),
        migrations.AddField(
            model_name='dinossauro',
            name='f_subordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur_management.Subordem'),
        ),
    ]
